# Generated by Django 3.2.14 on 2022-07-25 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='education',
            field=models.CharField(default=1, max_length=20, verbose_name='سطح تحصیلات'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='contact',
            name='first_name',
            field=models.CharField(max_length=30, verbose_name='نام'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='job',
            field=models.CharField(max_length=50, verbose_name='شغل'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='last_name',
            field=models.CharField(max_length=50, verbose_name='نام خانوادگی'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='phone',
            field=models.IntegerField(verbose_name='شماره تماس'),
        ),
    ]
